"""Join `kol_priors` to hand-resolved YouTube channel IDs → `youtube.toml` body.

Used by `scripts/bootstrap_youtube_from_kols.py`. Keeps seed data importable
from tests without executing the script entrypoint.
"""

from __future__ import annotations

import re
from textwrap import dedent

from ..generate.config import GeneratorConfig

# Slug keys MUST match `GeneratorConfig.kol_priors` (defaults or generator.toml).
# Values: (channel_id, default_author on Item when feed omits author).
YOUTUBE_SEED: dict[str, tuple[str, str]] = {
    "yannic kilcher": ("UCZHmQk67mSJgfCCTn7xBfew", "Yannic Kilcher"),
    "latent space": ("UCcO7fE1uD3UDtmyIJUw1VMA", "Latent Space"),
    "hamel husain": ("UC__dUuqF5w4OnbW221JxmKg", "Hamel Husain"),
    "harrison chase": ("UCC-lyoTfSrcJzA1ab3APAgw", "LangChain"),
    "jerry liu": ("UCeRjipR4_SsCddq9VZ2AeKg", "LlamaIndex"),
    "simon willison": ("UCYqc84mh-05GwxmHmtA4zcQ", "Simon Willison"),
    "jim fan": ("UC4vr9HaKGCYLmmiCXnzac7A", "Jim Fan"),
    "shane legg": ("UCP7jMXSY2xbc3KCAE0MHQ-A", "Google DeepMind"),
    "wolfram": ("UCJekgf6k62CQHdENWf2NgAQ", "Wolfram"),
}

# Same rule as `youtube_adapter` constructor (keep in sync).
_CHANNEL_ID_RE = re.compile(r"^UC[0-9A-Za-z_-]{20,30}$")


def validate_seed_channel_ids() -> None:
    for slug, (cid, _author) in YOUTUBE_SEED.items():
        if not _CHANNEL_ID_RE.match(cid):
            raise ValueError(f"youtube seed {slug!r}: invalid channel_id {cid!r}")


def missing_seed_slugs(cfg: GeneratorConfig) -> list[str]:
    return sorted(k for k in cfg.kol_priors if k not in YOUTUBE_SEED)


def render_youtube_toml(cfg: GeneratorConfig) -> str:
    """Return full `youtube.toml` text. Channel block order follows `kol_priors` key order."""

    validate_seed_channel_ids()
    priors = cfg.kol_priors
    lines: list[str] = []
    lines.append(
        dedent(
            """\
            # YouTube ingestion — generated by `scripts/bootstrap_youtube_from_kols.py`
            # (`python/rexy/sources/youtube_bootstrap.py`). Rex: verify each `channel_id`.
            #
            # `kol` must match a key in `kol_priors`. Transcripts: best-effort
            # (`youtube-transcript-api`); else description / metadata_only.

            source_type = "youtube"
            disabled    = false

            """
        ).rstrip()
    )

    for slug in priors:
        if slug not in YOUTUBE_SEED:
            continue
        cid, author = YOUTUBE_SEED[slug]
        lines.append("[[channels]]")
        lines.append(f'channel_id     = "{cid}"')
        lines.append(f'default_author = "{author}"')
        lines.append(f'kol            = "{slug}"')
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
