"""Interactive deep-note picker behavior."""

from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

import pytest

from rexy.corpus.items_store import ItemsStore
from rexy.corpus.selections_store import SelectionsStore
from rexy.domain import Item, PayloadKind, Scores, SelectionEntry, SourceType, Translations, Window
from rexy.generate.config import GeneratorConfig
from rexy.generate.deep_note_picker import (
    available_selection_ends,
    collect_deep_note_candidates,
    run_interactive_deep_note_pick,
)
from rexy.generate.llm.deep_note import MemoryDeepNoteWriter


WINDOW = Window.parse("2026-05-10/2026-05-17")


def _item(item_id: str, title: str, payload_ref: str | None = None) -> Item:
    return Item(
        id=item_id,
        source_type=SourceType.ARXIV,
        source_native_id=item_id.split(":", 1)[1],
        canonical_url=f"https://example.com/{item_id}",
        title=title,
        author="A",
        published_at=date(2026, 5, 14),
        type="paper",
        topics_raw=[],
        payload_kind=PayloadKind.EXTRACT if payload_ref else PayloadKind.METADATA_ONLY,
        payload_ref=payload_ref,
        fetched_at=datetime(2026, 5, 17, tzinfo=timezone.utc),
        adapter="test",
    )


def _entry(
    item_id: str,
    *,
    rank: int,
    composite: float,
    topics: list[str],
    tldr: str = "A useful result.",
) -> SelectionEntry:
    return SelectionEntry(
        item_id=item_id,
        window=WINDOW,
        rank=rank,
        scores=Scores(relevance=4.5, novelty=4.0, actionability=4.0, composite=composite),
        tldr_en=tldr,
        takeaways_en=["A", "B", "C"],
        implication_en="It matters.",
        topics=topics,
        translations=Translations(
            title_zh=f"标题 {item_id}",
            tldr_zh="摘要。",
            takeaways_zh=["甲", "乙", "丙"],
            implication_zh="重要。",
            topics_zh=["智能体", "模拟"] if "Simulation" in topics else ["智能体"],
        ),
        model="m",
        prompt_version="v",
        generated_at=datetime(2026, 5, 18, tzinfo=timezone.utc),
    )


def _populate(tmp_path: Path) -> Path:
    corpus = tmp_path / "corpus"
    (corpus / "payloads").mkdir(parents=True)
    (corpus / "payloads" / "bridge.txt").write_text("payload body", encoding="utf-8")
    ItemsStore(corpus / "items.jsonl").upsert_many([
        _item("arxiv:1", "World model eval", "bridge.txt"),
        _item("arxiv:2", "Agent-only infra"),
        _item("arxiv:3", "Agent architecture"),
    ])
    SelectionsStore(corpus / "selections").write(WINDOW, [
        _entry("arxiv:1", rank=1, composite=4.9, topics=["Agent", "Simulation"]),
        _entry("arxiv:2", rank=2, composite=4.8, topics=["Agent"]),
        _entry("arxiv:3", rank=3, composite=4.7, topics=["Agent"]),
    ])
    return corpus


def test_collect_candidates_requires_ai_and_simulation(tmp_path: Path) -> None:
    corpus = _populate(tmp_path)

    candidates, skipped = collect_deep_note_candidates(WINDOW, corpus, GeneratorConfig())

    assert [c.entry.item_id for c in candidates] == ["arxiv:1"]
    assert candidates[0].payload_chars == len("payload body")
    assert {s.entry.item_id for s in skipped} == {"arxiv:2", "arxiv:3"}
    assert all("Simulation signal" in s.reason for s in skipped)


def test_interactive_picker_writes_audit_toml_and_generates_note(tmp_path: Path) -> None:
    corpus = _populate(tmp_path)
    public_dir = tmp_path / "Weekly_Gist" / "Public"
    public_dir.mkdir(parents=True)
    (public_dir / "Weekly_Brief_Public_2026-05-17.md").write_text("public", encoding="utf-8")
    answers = iter(["y", "y", "y"])
    seen: list[str] = []

    run = run_interactive_deep_note_pick(
        window=WINDOW,
        corpus_root=corpus,
        public_dir=public_dir,
        picks_root=tmp_path / "corpus" / "deep_picks",
        inbox_dir=tmp_path / "KnowledgeCard_Inbox",
        config=GeneratorConfig(),
        writer_factory=lambda: MemoryDeepNoteWriter(),
        input_fn=lambda prompt: (seen.append(prompt) or next(answers)),
        output_fn=seen.append,
    )

    assert run.item_ids == ["arxiv:1"]
    assert len(run.written) == 1
    assert run.picks_file.read_text(encoding="utf-8").startswith(
        "# Generated by rexy deep-notes pick. Do not edit manually."
    )
    assert 'source = "public_top3_overview_ai_sim"' in run.picks_file.read_text(encoding="utf-8")
    assert "memory stub" in run.written[0].read_text(encoding="utf-8")
    assert "Accept section 00? [y/n]: " not in seen


def test_interactive_picker_zero_selected_does_not_create_picks_file(tmp_path: Path) -> None:
    corpus = _populate(tmp_path)
    public_dir = tmp_path / "Weekly_Gist" / "Public"
    public_dir.mkdir(parents=True)
    (public_dir / "Weekly_Brief_Public_2026-05-17.md").write_text("public", encoding="utf-8")
    answers = iter(["y", "n"])

    run = run_interactive_deep_note_pick(
        window=WINDOW,
        corpus_root=corpus,
        public_dir=public_dir,
        picks_root=tmp_path / "corpus" / "deep_picks",
        inbox_dir=tmp_path / "KnowledgeCard_Inbox",
        config=GeneratorConfig(),
        writer_factory=lambda: MemoryDeepNoteWriter(),
        input_fn=lambda _prompt: next(answers),
        output_fn=lambda _line: None,
    )

    assert run.item_ids == []
    assert not run.picks_file.exists()
    assert run.written == []


def test_existing_note_uses_yes_no_copy_prompt(tmp_path: Path) -> None:
    corpus = _populate(tmp_path)
    public_dir = tmp_path / "Weekly_Gist" / "Public"
    public_dir.mkdir(parents=True)
    (public_dir / "Weekly_Brief_Public_2026-05-17.md").write_text("public", encoding="utf-8")
    inbox_dir = tmp_path / "KnowledgeCard_Inbox"
    inbox_dir.mkdir()
    existing = inbox_dir / "deep_arxiv_1_2026-05-17.md"
    existing.write_text("keep me\n", encoding="utf-8")
    answers = iter(["y", "y", "y", "n", "y"])
    prompts: list[str] = []

    run = run_interactive_deep_note_pick(
        window=WINDOW,
        corpus_root=corpus,
        public_dir=public_dir,
        picks_root=tmp_path / "corpus" / "deep_picks",
        inbox_dir=inbox_dir,
        config=GeneratorConfig(),
        writer_factory=lambda: MemoryDeepNoteWriter(),
        input_fn=lambda prompt: (prompts.append(prompt) or next(answers)),
        output_fn=lambda _line: None,
    )

    assert existing.read_text(encoding="utf-8") == "keep me\n"
    assert run.written == [inbox_dir / "deep_arxiv_1_2026-05-17_2.md"]
    assert "Overwrite existing deep note? [y/n]: " in prompts
    assert "Create a suffixed copy instead? [y/n]: " in prompts


def test_interactive_picker_writes_generated_opening_without_edit_prompt(tmp_path: Path) -> None:
    corpus = _populate(tmp_path)
    public_dir = tmp_path / "Weekly_Gist" / "Public"
    public_dir.mkdir(parents=True)
    (public_dir / "Weekly_Brief_Public_2026-05-17.md").write_text("public", encoding="utf-8")
    answers = iter(["y", "y", "y"])
    prompts: list[str] = []

    run = run_interactive_deep_note_pick(
        window=WINDOW,
        corpus_root=corpus,
        public_dir=public_dir,
        picks_root=tmp_path / "corpus" / "deep_picks",
        inbox_dir=tmp_path / "KnowledgeCard_Inbox",
        config=GeneratorConfig(),
        writer_factory=lambda: MemoryDeepNoteWriter(),
        input_fn=lambda prompt: (prompts.append(prompt) or next(answers)),
        output_fn=lambda _line: None,
    )

    text = run.written[0].read_text(encoding="utf-8")
    assert "这条内容把 AI 能力放回到可试错的世界接口里看" in text
    assert "Accept section 00? [y/n]: " not in prompts
    assert "> " not in prompts


def test_interactive_picker_rejects_invalid_markdown_without_writing_note(tmp_path: Path) -> None:
    class BadWriter:
        model = "bad"

        def write(self, **_kwargs):
            return "# Bad\n\nNo strict KnowledgeCard structure.\n"

    corpus = _populate(tmp_path)
    public_dir = tmp_path / "Weekly_Gist" / "Public"
    public_dir.mkdir(parents=True)
    (public_dir / "Weekly_Brief_Public_2026-05-17.md").write_text("public", encoding="utf-8")
    inbox_dir = tmp_path / "KnowledgeCard_Inbox"
    answers = iter(["y", "y", "y"])

    with pytest.raises(ValueError, match="invalid deep note Markdown"):
        run_interactive_deep_note_pick(
            window=WINDOW,
            corpus_root=corpus,
            public_dir=public_dir,
            picks_root=tmp_path / "corpus" / "deep_picks",
            inbox_dir=inbox_dir,
            config=GeneratorConfig(),
            writer_factory=lambda: BadWriter(),
            input_fn=lambda _prompt: next(answers),
            output_fn=lambda _line: None,
        )

    if inbox_dir.exists():
        assert not list(inbox_dir.glob("*.md"))


def test_available_selection_ends_lists_recent_dates(tmp_path: Path) -> None:
    root = tmp_path / "corpus" / "selections"
    root.mkdir(parents=True)
    for raw in ["2026-05-17", "2026-05-10", "bad"]:
        (root / f"Selection_{raw}.jsonl").write_text("", encoding="utf-8")

    assert available_selection_ends(tmp_path / "corpus") == [
        date(2026, 5, 17),
        date(2026, 5, 10),
    ]
